# Generated by Django 3.0.4 on 2020-03-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField()),
                ('version', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('title', 'version')},
            },
        ),
    ]
