# Generated by Django 3.0.4 on 2020-03-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdatedPosts',
        ),
    ]
