# Generated by Django 3.0.4 on 2020-03-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_delete_updatedposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.Post')),
            ],
        ),
    ]
