# Generated by Django 3.0.4 on 2020-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_updatedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
